Added SOC paragraph
LibreSolar/learn.libre.solar pull request #58
Opened 2021-06-18 21:53 UTC by mulles

2021-06-18 21:55 UTC, mulles reviewed
corrected some typos

2021-06-21 06:55 UTC, martinjaeger requested changes
Thanks, looks good. Just fixed some typos.

2021-06-21 06:55 UTC, martinjaeger commented on docs/system/bms.md
> +The BMS is responsible to measure the voltage, current and temperature and stop or reduce dis-/charging in other to stay within defined safety limits of the cells.
```suggestion
The BMS is responsible to measure the voltage, current and temperature and stop or reduce dis-/charging in order to stay within defined safety limits of the cells.
```

2021-06-21 06:55 UTC, martinjaeger commented on docs/system/bms.md
> +It has a significant deviation due to the OCV not being accurately measurable during current flow. A more sophisticated algorithm consists of combining the voltage measurement with a current measurem
```suggestion
The SOC of the cells is calculated by combining current and voltage measurements, sometimes temperature.

The most simple SOC determination is done with an open circuit voltage (OCV) lookup table. 
It has a significant deviation due to the OCV not being accurately measurable during current flow. A more sophisticated algorithm consists of combining the voltage measurement with a current measurement, accumulating the current into or out of a cell, also known as coulomb counting. 
```

2021-06-21 06:55 UTC, martinjaeger commented on docs/system/bms.md
> +The current research on SOC estimation suggest, that a favourable algorithm to perform the combination of current and voltage is the extend kalman filter (EKF) or variation of it. This method is know
```suggestion
The current research on SOC estimation suggests that a favorable algorithm to perform the combination of current and voltage is the extended Kalman filter (EKF) or variations of it. This method is known as sensor fusion and is well established. More advanced methods use an equivalent circuit model of the cell (ECM) in order to account for changing cell characteristics like internal resistance. These methods not only provide a better SOC, but also the state of health (SOH) of the battery. Good literature by Dr. Gregory L. Plett on implementation of such algorithms can be found [here](http://mocha-java.uccs.edu/ECE5720/index.html).
```

2021-06-21 10:26 UTC, mulles commented on docs/system/bms.md
> +The BMS is responsible to measure the voltage, current and temperature and stop or reduce dis-/charging in other to stay within defined safety limits of the cells.
thx

2021-06-21 10:28 UTC, mulles commented on docs/system/bms.md
> +The current research on SOC estimation suggest, that a favourable algorithm to perform the combination of current and voltage is the extend kalman filter (EKF) or variation of it. This method is know
thx for fixing.

2021-06-23 13:07 UTC, martinjaeger commented
@mulles the issues are not yet resolved. You have to commit the suggestions. Just clicking "resolved" does not change anything. But I'll do that now, assuming you agree to the suggestions.

2021-06-23 13:08 UTC, martinjaeger approved these changes

2021-06-23 13:08 UTC, merged