Correction of Balancing
LibreSolar/learn.libre.solar pull request #60
Opened 2021-06-18 22:09 UTC by mulles

Illustrated the statement with the circuit of https://github.com/LibreSolar/bms-15s80-sc/blob/master/LibreSolar_BMS48V_schematic.pdf
I haven't seen a circuit bleeding current to common ground (0V reference), thus I question that even exists, as it would reduce the current charging the other cells? 

TODO: the image should be uploaded to the repo and should be .svg, adding some arrows [1] showing the current flow and maybe the chip switching the MOSFET would be a good addition. Nice to have would be  autogeneration of the illustration whenever the circuit changes. A link to the bms-15s80-sc could be added as well. 

[1] Resource: https://www.avdweb.nl/solar-bike/electronics/bms

2021-06-18 22:15 UTC, mulles reviewed
more detailed

2021-06-18 22:21 UTC, mulles commented
I removed the part suggesting a fixed resistor in parallel as it adds confusion/complexity without much advantage. Moreover it has really poor performance. A great resource for the topic is: http://mocha-java.uccs.edu/ECE5720/ECE5720-Notes05.pdf

2021-06-18 22:24 UTC, mulles reviewed
corrected some typos

2021-06-21 06:37 UTC, martinjaeger requested changes
If you want to add an image for additional explanation, it has to be committed to the git repository itself. In addition to that, it should be re-drawn with Inkscape to contain only the necessary parts and in order to have the same look for all schematics in this document.

I think it's not strictly necessary to have an image here. So I suggest rewriting the text as below.

I agree that the previous text was not 100% accurate.

2021-06-21 06:37 UTC, martinjaeger commented on docs/system/bms.md
> +![image](https://user-images.githubusercontent.com/13488510/122396568-660bb300-cf78-11eb-8798-1d3904f9fe4d.png)
```suggestion
Passive balancing can be done by converting excessive charge to heat using a resistor. The resistor is connected in parallel to the cell and switched on with a transistor for the cells with higher voltage, thus excessive charge in comparisons to the other cells in series. Passive balancing slightly increases the thermal energy dissipated by the pack and decreases the overall efficiency.
```

2021-06-21 09:35 UTC, mulles reviewed
Ready to merge.

2021-06-21 10:01 UTC, martinjaeger approved these changes

2021-06-21 10:02 UTC, merged